language: bash
before_install: 
 - sudo apt-get update -qq
 - sudo apt-get install -qq shunit2
 - # Configure git enough for it not to error
 - git config --global user.email "devnull@example.com"
 - git config --global user.name "Foo Bar"
script: shunit2 tests/test_rstash
